export {default as Navbar} from './Navbar'
export {default as Intro} from './Intro'
export {default as About} from './About'
export{default as Footer} from './Footer'
export{default as Education} from './Education'
export{default as Projects} from './Projects'
export{default as CommPortfolio} from './CommPortfolio'
export{default as Resume} from './Resume'